        { name: "Pulse", beatsInCycle: 4, note: "A2", waveform: "kick", volume: 0.24, simplicity: 80, pan: 0, color: COLORS[6] },
      ],
    }),
    "Deep Ambient": () => ({
      bpm: 38,
      useBpm: true,
      masterSimplicity: 80,
      reverbWet: 0.66,
      delayWet: 0.34,
      evolve: true,
      evolveRate: 0.14,
      visualMode: "pendulum",
      voices: [
        { name: "Void", beatsInCycle: 2, note: "C2", waveform: "pad", volume: 0.40, simplicity: 88, pan: 0, color: "#5a4a9a" },
        { name: "Orbit", beatsInCycle: 3, note: "G2", waveform: "sine", volume: 0.32, simplicity: 82, pan: -0.35, color: COLORS[1] },
        { name: "Drift", beatsInCycle: 7, note: "A3", waveform: "triangle", volume: 0.22, simplicity: 78, pan: -0.12, color: COLORS[4] },
        { name: "Spark", beatsInCycle: 5, note: "D4", waveform: "bell", volume: 0.14, simplicity: 72, pan: 0.40, color: COLORS[2] },
        { name: "Core", beatsInCycle: 1, note: "C1", waveform: "kick", volume: 0.26, simplicity: 90, pan: 0, pitchMode: "hz", hz: 38, color: COLORS[6] },
      ],
    }),
    "Space Lullaby": () => ({
      bpm: 42,
      useBpm: true,
      masterSimplicity: 82,
      reverbWet: 0.58,
      delayWet: 0.28,
      evolve: true,
      evolveRate: 0.06,
      visualMode: "pendulum",
      voices: [
        { name: "Cradle", beatsInCycle: 3, note: "F3", waveform: "sine", volume: 0.36, simplicity: 86, pan: -0.22, color: "#7ec8ff" },
        { name: "Hush", beatsInCycle: 2, note: "C3", waveform: "pad", volume: 0.32, simplicity: 90, pan: 0.28, color: "#9b7cff" },
        { name: "Star", beatsInCycle: 5, note: "A4", waveform: "bell", volume: 0.16, simplicity: 80, pan: 0.45, color: "#6eb8ff" },
        { name: "Moon", beatsInCycle: 4, note: "D4", waveform: "triangle", volume: 0.22, simplicity: 84, pan: -0.40, color: "#a890ff" },
        { name: "Breath", beatsInCycle: 1, note: "F2", waveform: "sine", volume: 0.30, simplicity: 92, pan: 0, color: "#5a6a9a" },
      ],
    }),

    "Sine Rhythms": () => ({
      bpm: 50,
      useBpm: true,
      masterSimplicity: 58,
      reverbWet: 0.48,
      delayWet: 0.28,
      evolve: true,
      evolveRate: 0.1,
      visualMode: "sineRibbons",
      voices: [
        { name: "Ribbon 1", beatsInCycle: 9, note: "E4", waveform: "sine", volume: 0.32, simplicity: 55, pan: -0.45, color: COLORS[0] },
        { name: "Ribbon 2", beatsInCycle: 8, note: "B3", waveform: "triangle", volume: 0.34, simplicity: 58, pan: -0.2, color: COLORS[2] },
        { name: "Ribbon 3", beatsInCycle: 7, note: "G3", waveform: "sine", volume: 0.36, simplicity: 60, pan: 0.05, color: COLORS[1] },
        { name: "Ribbon 4", beatsInCycle: 6, note: "D3", waveform: "pad", volume: 0.38, simplicity: 62, pan: 0.25, color: COLORS[5] },
        { name: "Ribbon 5", beatsInCycle: 5, note: "A2", waveform: "sine", volume: 0.4, simplicity: 65, pan: 0.45, color: COLORS[3] },
      ],
    }),
    "Mandala": () => ({
      bpm: 54,
      useBpm: true,
      masterSimplicity: 50,
      reverbWet: 0.42,
      delayWet: 0.24,
      evolve: true,
      evolveRate: 0.12,
      visualMode: "mandala",
      voices: [
        { name: "Petal A", beatsInCycle: 8, note: "C4", waveform: "bell", volume: 0.3, simplicity: 45, pan: -0.3, color: COLORS[0] },
        { name: "Petal B", beatsInCycle: 7, note: "E4", waveform: "sine", volume: 0.32, simplicity: 48, pan: 0.3, color: COLORS[1] },
        { name: "Petal C", beatsInCycle: 6, note: "G4", waveform: "triangle", volume: 0.28, simplicity: 50, pan: -0.15, color: COLORS[2] },
        { name: "Petal D", beatsInCycle: 5, note: "B3", waveform: "pad", volume: 0.35, simplicity: 55, pan: 0.15, color: COLORS[4] },
        { name: "Core", beatsInCycle: 3, note: "C3", waveform: "sine", volume: 0.45, simplicity: 60, pan: 0, color: COLORS[6] },
      ],
    }),
    "Spinning Triangles": () => ({
      bpm: 64,
      useBpm: true,
      masterSimplicity: 42,
      reverbWet: 0.35,
      delayWet: 0.2,
      evolve: false,
